name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: dotnet restore
      run: dotnet restore src/OneBitSoftware.Slovom.sln

    - name: dotnet build
      run: dotnet build --no-restore --configuration Release src/OneBitSoftware.Slovom.sln

    - name: dotnet test
      run: dotnet test --no-build --configuration Release --verbosity normal src/OneBitSoftware.Slovom.sln

    - name: dotnet pack
      run: dotnet pack --configuration Release --no-build src/OneBitSoftware.Slovom/OneBitSoftware.Slovom.csproj

    - name: dotnet nuget push
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push bin/Release/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json